# Generated by Django 3.2.7 on 2021-11-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ministry_of_health',
            field=models.BooleanField(default=False),
        ),
    ]
