# Generated by Django 3.2.7 on 2021-11-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperatures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
